events {
    worker_connections 1024;
}
http {
    upstream url_shortening_service {
        server url_shortening_service:8100;
    }
    upstream auth_service {
        server auth_service:8101;
    }
    server {
        listen 80;
        location /apidocs/ {
            alias /etc/nginx/apidocs/;
            index index.html;
            try_files $uri $uri/ =404;
        }
        location ~ ^/users {
            proxy_pass         http://auth_service;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
        location / {
            proxy_pass         http://url_shortening_service;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
    }
}
